default:
  course_name_long: "Epi/Biostats Summer Institute - Introduction to R for Public Health Researchers 140.604.73"
  course_dates: "January 8-12 and 16-19, 2024"
  course_time: "1:30 p.m. - 4:50 p.m. ET"
  final_due_date: "January 24th at 11:59pm ET"
  grades_due: "January 26"
  holiday: "In recognition of [Martin Luther King Jr. Day](https://en.wikipedia.org/wiki/Martin_Luther_King_Jr._Day), there will be **no class on Monday January 15th, 2024**."
  courseplus_web: "https://courseplus.jhu.edu/core/index.cfm/go/syl:syl.public.view/coid/20749/"
  courseplus_dropboxes: "https://courseplus.jhu.edu/core/index.cfm/go/db:main/coID/20749/"
  google_survey: "https://forms.gle/rTqJ4qwV2boo3FL78"
  slack_workspace: "https://intro-to-r-140-604.slack.com/"
  ta: "Padmashri Saravanan (psarava1 at jhu.edu), Alex Newman (anewma28 at jhu.edu)"
  instructors: "[Carrie Wright](https://carriewright11.github.io/) (cwrigh60 at jhu.edu), [Ava Hoffman](https://www.avahoffman.com/) (ava.hoffman at jhu.edu), [Clifton McKee](https://clifmckee.github.io/) (cmckee7 at jhu.edu)"
  r_version: "(4.3.2 (called 'Eye Holes') as of October 31, 2023)"
  r_dl_mac_m1: "https://cran.r-project.org/bin/macosx/big-sur-arm64/base/R-4.3.2-arm64.pkg"
  r_dl_mac_intel: "https://cran.r-project.org/bin/macosx/big-sur-x86_64/base/R-4.3.2-x86_64.pkg"
  r_dl_windows: "https://cran.r-project.org/bin/windows/base/R-4.3.2-win.exe"
  rstudio_dl_mac: "https://download1.rstudio.org/electron/macos/RStudio-2023.12.0-369.dmg"
  rstudio_dl_windows: "https://download1.rstudio.org/electron/windows/RStudio-2023.12.0-369.exe"

