##### Checks run at pull request #####
# Check quiz formatting
check-quizzes: no
# Check that urls in the content are not broken
url-checker: yes
# Render preview of content with changes (Rmd's and md's are checked)
render-preview: yes
# Spell check Rmds and quizzes
spell-check: yes
# Style any R code
style-code: no
# Test build the docker image if any docker-relevant files have been changed
docker-test: no


# Autogenerate Labs from Keys (clear the Rmarkdown chunks)
make-labs: yes

# What docker image should be used for rendering?
rendering-docker-image: 'jhudsl/intro_to_r:1.1.1'
